# Generated by Django 5.2.7 on 2025-10-26 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0002_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='borrador', max_length=12),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['slug'], name='carrito_pro_slug_2c4946_idx'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(condition=models.Q(('stock__gte', 0)), name='producto_stock_no_negativo'),
        ),
    ]
