# Generated by Django 5.2.7 on 2025-10-28 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0003_orden_estado_producto_carrito_pro_slug_2c4946_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='producto',
            name='carrito_pro_slug_2c4946_idx',
        ),
        migrations.AddField(
            model_name='orden',
            name='apellido',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='orden',
            name='direccion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='orden',
            name='dni',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='orden',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('tarjeta', 'Tarjeta de crédito/débito'), ('mercadopago', 'MercadoPago'), ('efectivo', 'Efectivo/Pago en sucursal')], default='tarjeta', max_length=30),
        ),
        migrations.AddField(
            model_name='orden',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='orden',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
