# Generated by Django 5.2.7 on 2025-11-02 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0004_remove_producto_carrito_pro_slug_2c4946_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='apellido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='orden',
            name='direccion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='orden',
            name='dni',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='orden',
            name='metodo_pago',
            field=models.CharField(choices=[('tarjeta', 'Tarjeta de crédito/débito'), ('mercadopago', 'MercadoPago'), ('efectivo', 'Efectivo/Pago en sucursal')], max_length=30),
        ),
        migrations.AlterField(
            model_name='orden',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['slug'], name='carrito_pro_slug_2c4946_idx'),
        ),
    ]
